<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
   <modelVersion>4.0.0</modelVersion>

   <groupId>org.tmt.aps.peas</groupId>
   <artifactId>pcs-web</artifactId>
   <version>0.3.0</version>
   <packaging>war</packaging>
   <name>PCS-WEB</name>

   <licenses>
      <license>
         <name>GNU Lesser General Public License</name>
         <url>http://www.gnu.org/copyleft/lesser.html</url>
         <distribution>repo</distribution>
      </license>
   </licenses>

     <properties>
        <!-- the Maven project should use the minimum Java SE version supported -->
        <maven.compiler.release>17</maven.compiler.release>
        <!-- the version for the Server -->
        <version.server>35.0.1.Final</version.server>
        <!-- the versions for BOMs, Packs and Plugins -->
        <version.bom.ee>${version.server}</version.bom.ee>
        <version.plugin.wildfly>5.1.1.Final</version.plugin.wildfly>
    </properties>



     


   <pluginRepositories>
      <pluginRepository>
         <id>jboss-public-repository</id>
         <name>JBoss Repository</name>
         <url>https://repository.jboss.org/nexus/content/groups/public</url>
         <releases>
            <enabled>true</enabled>
         </releases>
         <snapshots>
            <enabled>false</enabled>
         </snapshots>
      </pluginRepository>
   </pluginRepositories>

    <dependencyManagement>
        <dependencies>
            <!-- importing the ee-with-tools BOM adds specs and other useful artifacts as managed dependencies -->
            <dependency>
                <groupId>org.wildfly.bom</groupId>
                <artifactId>wildfly-ee-with-tools</artifactId>
                <version>${version.bom.ee}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

   <dependencies>

         <!-- Import the CDI API, we use provided scope as the API is included in JBoss EAP -->
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Import the Common Annotations API (JSR-250), we use provided scope
        as the API is included in JBoss EAP -->
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
		    <groupId>jakarta.inject</groupId>
		    <artifactId>jakarta.inject-api</artifactId>
		    <scope>provided</scope>
		</dependency>

        <!-- Import the EJB API, we use provided scope as the API is included in JBoss EAP -->
        <dependency>
            <groupId>jakarta.ejb</groupId>
            <artifactId>jakarta.ejb-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Import the JSF API, we use provided scope as the API is included in JBoss EAP -->

		
		<dependency>
		    <groupId>jakarta.faces</groupId>
		    <artifactId>jakarta.faces-api</artifactId>
		    <scope>provided</scope>
		</dependency>
		
		<dependency>
		    <groupId>jakarta.servlet</groupId>
		    <artifactId>jakarta.servlet-api</artifactId>
		    <scope>provided</scope>
		</dependency>

        <!-- Tests -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

 
		<dependency>
		    <groupId>jakarta.persistence</groupId>
		    <artifactId>jakarta.persistence-api</artifactId>
		    <scope>provided</scope>
		</dependency>
		
		  <!-- Transaction API (also provided) -->
		<dependency>
		    <groupId>jakarta.transaction</groupId>
		    <artifactId>jakarta.transaction-api</artifactId>
		    <scope>provided</scope>
		</dependency>

		
		<dependency>
		    <groupId>org.primefaces</groupId>
		    <artifactId>primefaces</artifactId>               
		    <version>14.0.0</version>
		    <classifier>jakarta</classifier>
		    <exclusions>
		        <exclusion>
		            <groupId>jakarta.el</groupId>
		            <artifactId>jakarta.el-api</artifactId>
		        </exclusion>
		    </exclusions>
		</dependency>
        
        
		<dependency>
		  <groupId>org.jboss.logging</groupId>
		  <artifactId>jboss-logging</artifactId>
		  </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.7</version>
        </dependency>


	  <dependency>
		<groupId>commons-beanutils</groupId>
		<artifactId>commons-beanutils</artifactId>
		</dependency>
	  
	  <dependency>
		<groupId>commons-collections</groupId>
		<artifactId>commons-collections</artifactId>
		</dependency>
	
	  <dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-io</artifactId>
		<version>1.3.2</version>
	  </dependency>
	  
	  <dependency>
		<groupId>commons-fileupload</groupId>
		<artifactId>commons-fileupload</artifactId>
		<version>1.2.2</version>
	  </dependency>
	 
	 <dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-math3</artifactId>
		<version>3.2</version>
	</dependency>
	 
	<dependency>
		<groupId>com.googlecode.json-simple</groupId>
		<artifactId>json-simple</artifactId>
		<version>1.1</version>
	</dependency>

	<dependency>
		<groupId>edu.ucar</groupId>
		<artifactId>netcdf</artifactId>
		<version>4.2</version>
	</dependency>

	<dependency>
		<groupId>log4j</groupId>
		<artifactId>log4j</artifactId>
		<version>1.2.17</version>
		<scope>provided</scope>
	</dependency>


	<dependency>
		<groupId>org.tmt.aps.peas</groupId>
		<artifactId>pcs-extinf</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</dependency>

	<dependency>
		<groupId>org.tmt.aps.peas</groupId>
		<artifactId>pcs-extinf-impl</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</dependency>
		
	<dependency>
		<groupId>org.keck</groupId>
		<artifactId>pcs-cam-async-rpc</artifactId>
		<version>1.0</version>
	</dependency>
  
	<dependency>
		<groupId>org.keck</groupId>
		<artifactId>pcs-ccd-rpc</artifactId>
		<version>1.0</version>
	</dependency>
	
	<dependency>
		<groupId>org.keck</groupId>
		<artifactId>acs-extint-common</artifactId>
		<version>1.0</version>
	</dependency>
	
	<dependency>
		<groupId>org.keck</groupId>
		<artifactId>acs-extint-gwy-rpc</artifactId>
		<version>1.0</version>
	</dependency>
	
	<dependency>
		<groupId>org.keck</groupId>
		<artifactId>pcs-rsk-rpc</artifactId>
		<version>1.0</version>
	</dependency>
	
	<dependency>
		<groupId>org.keck</groupId>
		<artifactId>magiq-libs</artifactId>
		<version>1.0</version>
	</dependency>
	
	<!-- -->
	<dependency>
		<groupId>org.keck</groupId>
		<artifactId>KtlJava</artifactId>
		<version>1.0</version>
	</dependency>
	 
	<dependency>
		<groupId>org.keck</groupId>
		<artifactId>oncrpc</artifactId>
		<version>1.0</version>
	</dependency>

   </dependencies>

   <build>
        <!-- Set the name of the WAR, used as the context root when the app is deployed. -->
        <finalName>${project.artifactId}</finalName>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.wildfly.plugins</groupId>
                    <artifactId>wildfly-maven-plugin</artifactId>
                    <version>${version.plugin.wildfly}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
		<plugin>
		    <groupId>org.apache.maven.plugins</groupId>
		    <artifactId>maven-compiler-plugin</artifactId>
		    <version>3.11.0</version>
		    <configuration>
		        <release>21</release>
		    </configuration>
		</plugin>

            <plugin>
            	<groupId>org.apache.maven.plugins</groupId>
            	<artifactId>maven-war-plugin</artifactId>
            	<version>3.3.2</version> <!-- Latest stable release -->
        	</plugin>
        </plugins>
    </build>

    <repositories>
    

    <repository>
        <id>central</id>
        <name>Maven Central</name>
        <url>https://repo1.maven.org/maven2/</url>
    </repository>


        <repository>
            <id>jboss-public-maven-repository</id>
            <name>JBoss Public Maven Repository</name>
            <url>https://repository.jboss.org/nexus/content/groups/public/</url>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </snapshots>
            <layout>default</layout>
        </repository>
         
           
		<repository>
		    <id>prime-repo</id>
		    <name>PrimeFaces Maven Repository</name>
		    <url>https://repository.primefaces.org</url>
		    <layout>default</layout>
		 </repository>
		 
	   <repository>
        	<id>primefaces</id>
        	<url>https://repository.primefaces.org</url>
    	</repository>
		 
	</repositories>
	
</project>

